### ISSUE TITLE
Update for Solr 6.0.0

### ISSUE THREAD

**Issue by schrepfler** [kohesive/solr-undertow#29]
As per title.

**Comment by apatrida** [comment]
Solr 6.0.0 should work unless there was a final change since I last checked it, I'll update to have a distribution.  Do you see a specific problem with 6.0.0?

**Comment by apatrida** [comment]
ok, obviously changes did come in.  I'll check it over the next few days, unless it is something simple, I'm travelling and hard to take more than a few minutes to look at it.  Checking now and hoping it is easy.

**Comment by apatrida** [comment]
ok, took a look, I think it is the custom classloader not loading resource files from the Solr JAR, if only that, is easy fix.

**Comment by apatrida** [comment]
Fixed in release 1.6.1-RC-1

please test.
