### ISSUE TITLE
Provide packages for Solr 6.1 and Solr 5.5.2

### ISSUE THREAD

**Issue by stephlag** [kohesive/solr-undertow#32]
These are the latest available versions

**Comment by apatrida** [comment]
I'm not sure I want to do full distributions anymore, they aid mostly first time users and not sure how many come along that fit that category anymore.

**Comment by schrepfler** [comment]
I think it brings value. I've tried building my own solr-undertow and it doesn't seems to be able to build from master at the moment or it requires some settings property files which go beyond `./gradlew build distAll` (actually, should distAll even be used for local publish?)
I've had to setup a local gradle.properties with my bintray credentials to make it build and then it fails with 
```
uy.kohesive.solr.undertow.tests.TestServerWithPlugin > classMethod FAILED
    java.lang.AssertionError at TestServerWithPlugin.kt:-1

uy.kohesive.solr.undertow.tests.TestServerWithPlugin > classMethod FAILED
    kotlin.UninitializedPropertyAccessException at TestServerWithPlugin.kt:-1
```

Doesn't appear to be very approachable.
Distros are very consumable for both first time users and non.

**Comment by schrepfler** [comment]
It would be nice if this project would be cleaned up as a new started can't just build a distro, there's either something broken or more info is needed in the readme as far as the setup goes on a virgin machine. Solr 6.2.0 is out btw.

**Comment by apatrida** [comment]
build issue for missing bintray credentials is #34 , fixed on master

**Comment by apatrida** [comment]
What is the reason for building a local distribution?  `distAll` builds a `zip` and `tgz` you can build `distZip` o `distTar` to build one or the other.  Or you can `installDist` to not build either and have an exploded version created.  See the [Gradle Application Plugin](https://docs.gradle.org/current/userguide/application_plugin.html) ...  Unless you are changing souce code and customizing the build, there is no reason to build a local distribution.

For distributions that include Solr within them use `distWithSolr` for a `tgz` and `distZipWihSol` for a `zip` file.

**Comment by apatrida** [comment]
There are too many versions of Solr in use to provide distributions that include Solr.  And the distributions are large.  People can easily download the Solr zip files.  And most likely they already have the distribution since they have been using Sol before.

**Comment by apatrida** [comment]
(if you have issues with building, please provide a separate issue, and use the `--stacktrace` option so you can include a stacktrace.  The issue you hit might be from a change in the abstract base class for `ExtendedQueryBase` which is fixed on maser)

**Comment by apatrida** [comment]
I added quick links to Solr distributions in the README
https://github.com/kohesive/solr-undertow/blob/master/README.md#solr-distributions

**Comment by apatrida** [comment]
found missing files that would have affected your build (also broke circle-ci) and that has been fixed.

**Comment by schrepfler** [comment]
Thanks, with the new example from master and placed on last release example directory it "just works" (hope a release lands in as well.) I can't remember now but IIRC the step _Building Your Own Binary_ in the README.md must have been missing some pre-setup (creating config for gradle, credentials file?) which I suppose not all Java devs use day to day.

**Comment by apatrida** [comment]
you no longer need credentials in gradle properties.  I check for existance before using to avoid this.
