### ISSUE TITLE
Upgrade to Java 8 to match required Solr 6 version

### ISSUE THREAD

**Issue by stephlag** [kohesive/solr-undertow#33]
Java 8 is now a requirement for Solr 6.
Is there a reason to keep building with Java 7?

**Comment by apatrida** [comment]
Solr 4/5 do not have that requirement and there is no gain from targeting Java 8 when they can easily run on Java 8 if they wish.

**Comment by stephlag** [comment]
OK. I thought this build https://circleci.com/gh/kohesive/solr-undertow/42 failed because of this requirement.

**Comment by stephlag** [comment]
It should be built with JDK 8 targeting Java 7
