### ISSUE TITLE
Question about logging

### ISSUE THREAD

**Issue by heathprovost** [kohesive/solr-undertow#38]
Basically, is there a way to get the Solr console logging display to show the logs? I cant figure out how to get that to work... The logs are setup fine and I can view them from cmdline and whatnot, but the console just spins forever when you click the logging tab

**Comment by apatrida** [comment]
It might be that SOLR expects logs to be in a known location and format, and we are using a different logger here and a different location.  If you set `SOLR_LOGS_DIR` to point at the directory of the logs, does this cause the admin logging to show the log files?  (it might also be looking for `solr.log` by default)

**Comment by apatrida** [comment]
Taking a look at the code, it seems there is a `LogWatcher` plugin model to watch logging and record it for later use.  That might need to be adapted to work with the logback logging used in solr-undertow for the admin UI to function.

**Comment by apatrida** [comment]
important classes in case anyone wants to look into this:

* [LogWatcher](https://github.com/apache/lucene-solr/blob/master/solr/core/src/java/org/apache/solr/logging/LogWatcher.java)
* [LogWatcher registration](https://github.com/apache/lucene-solr/blob/master/solr/core/src/java/org/apache/solr/logging/LogWatcher.java#L127)

Assuming this is where the admin UI picks up logging data, just create a new `LogWatcher` implementation that works with our logging, and then register it with the static method on `LogWatcher`.

**Comment by heathprovost** [comment]
I know this is a year later, but if anyone needs this someone actually wrote a working implementation ages ago and I just found it recently: https://github.com/ottovazquez/solr-logback-watcher

All I did was build it with maven and put the jar into /lib and it worked, no changes required (for Solr 8.0 anyway). Basically just mimics the builtin one.
